### ISSUE TITLE
Not usable on CI

### ISSUE THREAD

**Issue by soumyadipDe** [ubirak/docker-php#14]
I tried your hack on our CI but container failed with "the input device is not a TTY". I understand it would not be possible to show progress bar but it should be possible to let the container running until stack is deployed with a proper message.

**Comment by shouze** [comment]
@soumyadipDe ok what's you CI solution?

This is probably a docker cli error because yes - your CI don't provide a tty - can you please try to run this command in place (notice the `-it` option removed)?
```
docker run -u root --rm -v /var/run/docker.sock:/var/run/docker.sock karibbu/docker-php:latest stack:converge myStack
```

I will add some instructions in the troubleshooting section of your README if it fixes your issue.

**Comment by shouze** [comment]
@soumyadipDe closing this issue, please reopen it if the given solution don't work for you.
